media:
  input: sources/media
  output: _site/media
content:
  - name: accueil
    label: Accueil
    type: file
    path: sources/_data/page/accueil.json
    fields:
      - name: titre
        label: Titre
        type: string
      - name: description
        label: Description de la page
        type: string
        description: 160 caractères recommandé
      - name: list
        label: Liste non ordonnée
        type: object
        list: true
        fields: 
          - name : labal
            label : Intitulé
            type : string
          - name : objectTypeList
            label : list
            type : object
            list: true
            fields: 
              - name : bullet
                label : Intitulé
                type : string
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [ Tech, News, Sports ]
      - name: body
        label: Body
        type: code
        options:
          language: html
      - name: featured_post
        label: Featured Post
        type: reference
        options:
          collection: accueilListe
  - name: accueilListe
    label: Accueil liste
    type: collection
    list: true
    path: sources/_data/page/accueilListe.json
    fields:
      - name: labal
        label: Intitulé
        type: string