media:
  input: sources/media
  output: _site/media
content:
  - name: accueil
    label: Accueil
    type: file
    path: sources/_data/page/accueil.json
    fields:
      - name: titre
        label: Titre
        type: string
