media:
  input: sources/media
  output: _site/media
content:
  - name: accueil
    label: Accueil
    type: file
    path: sources/_data/page/accueil.json
    fields:
      - name: titre
        label: Titre
        type: string
      - name: description
        label: Description de la page
        type: string
        description: 160 caractères recommandé
      - name: list
        label: Liste non ordonnée
        type: collection
        fields: 
          - name : labal
            label : Intitulé
            type : string
          
